# docker-compose.yml
version: "3"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - 8000:80

  db:
    image: mariadb
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1

  composer:
    image: composer:2.5.8
    command: [ "composer", "install" ]
    depends_on:
      - web
    volumes:
      - ./:/app


